### ISSUE TITLE
add setup.py, list dependencies

### ISSUE THREAD

**Issue by mattjj** [HIPS/pgmult#4]
Our dependencies should be pip-installable, too!

**Comment by slinderman** [comment]
I made pypolyagamma, pylds, and gslrandom pip-installable. I also updated the pgmult's setup.py and added a MANIFEST.in file in case we want to add this to pypi in the future too.  See https://github.com/HIPS/pgmult/commit/bd6602f79a10aed722ac26b615cd324c82534372.
