### ISSUE TITLE
problem with GPy

### ISSUE THREAD

**Issue by kayhan-batmanghelich** [HIPS/pgmult#8]
Hi Scott and Matt,

Really sorry that I am sending the second issue in one day. I interested to use `pgmult` with GP which is explain in `examples/multinomial_gp.py`. 

```
$ python examples/multinomial_gp.py
This program needs access to the screen.
Please run with a Framework build of python, and only when you are
logged in on the main display of your Mac.
```

It seems it is an issue with GPy but not sure. If you feel this is not relevant to your package, please close it.

Thanks,
Kayhan

**Comment by kayhan-batmanghelich** [comment]
It seems the issue is with wx backend. If I run the code with `pythonw examples/multinomial_gp.py` it runs.

ref: http://stackoverflow.com/questions/24134850/wxpython-on-python-3-miniconda-environment

**Comment by mattjj** [comment]
Hmm so should we close this issue, or is there something to fix in pgmult here?

**Comment by kayhan-batmanghelich** [comment]
`multinomial_gp.py` needs `GPy` package and `GPy` needs `wx`. I opened this issue with `GPy`:

https://github.com/SheffieldML/GPy/issues/387

It seems `wx` is somewhat broken in mac if I understand it correctly from here:

http://matplotlib.org/faq/virtualenv_faq.html

So, you can close this issue. I don't think you can fix it because there is something wrong with `GPy` dependency.

Thanks,

**Comment by mattjj** [comment]
Cool, thanks for the thorough investigation!

**Comment by kayhan-batmanghelich** [comment]
Response from the GPy issue:
"
Yes try using python3 and import matplotlib before importing GPy. Also look at your ipython config, which should say backend=macosx.
"

can I use pgmult with python3 ?

**Comment by mattjj** [comment]
I don't think we've ever tried it so there would probably be some bumps with python 3, but nothing should be impossible to update.
